<?php

/**
 * Implements hook_slack_receive_slash_command().
 */
function slack_receive_example_slack_receive_slash_command($command, $text) {
  $result = [];

  // React to /repeat command.
  if ($command == 'repeat') {

    // Answser must follow Slash message API format
    // @see https://api.slack.com/docs/message-formatting
    // NOTE: you can use BBCode as per documentation, or HTML as below,
    // it will be converted for you.
    // @see \Drupal\slack_receive\Encoder\SlackJsonEncoder
    $result = [
      'text' => t('Repeat bot: <i>@text</i>', ['@text' => $text]),
    ];
  }
  return $result;
}